development:
  clients:
    default:
      database: test
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: test
      hosts:
        - localhost:27017
